repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: fix-byte-order-marker
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: no-commit-to-branch
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.4
  hooks:
    - id: autopep8
      args: ['--max-line-length=179', '-i']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
      args: ['--no-strict-optional', '--scripts-are-modules', '--ignore-missing-imports', '-i']
- repo: https://github.com/PyCQA/pylint
  rev: pylint-2.6.0
  hooks:
    - id: pylint
      # Most of these options are way too permissive.
      # The intent is to remove them one by one. Tickets have been made.
      args:
        # These options should be kept
        - '--max-attributes=15'
        - '--disable=too-few-public-methods'
        - '--disable=no-else-return'
        - '--disable=import-error'
        - '--disable=broad-except'
        - '--disable=inconsistent-return-statements'
        # Below are the temporary permissive options
        - '--max-line-length=179' # Ideally 119, 79 is way too low
        - '--disable=duplicate-code'
        - '--disable=missing-function-docstring'
        - '--disable=missing-module-docstring'
        - '--disable=logging-format-interpolation'
        - '--disable=logging-not-lazy'
        - '--disable=too-many-statements'
        - '--disable=invalid-name'
        - '--disable=too-many-branches'
        - '--disable=too-many-nested-blocks'
        - '--disable=too-many-locals'
        - '--disable=too-many-arguments'
        - '--disable=global-variable-undefined'
