# This configuration file contains default values for CloudEndure migration factory

# Environment name (this is a logical container for default values - can represent a wave, a workload, an account or a simple configuration preset
# You can duplicate this block if you have multiple environments
environment:
  # Subnet where the replication servers for CloudEndure will be created
  replication_subnet_id: subnet-0a512345678
  # Default bandwidth (in Mbps throttling for new CloudEndure project (0 means infinite)
  replication_bandwidth_throttling:  0
  # Whether or not to disable public CloudEndure as proxy for replication
  replication_disable_public: True
  # Instance type for converter instances for any new CloudEndure project
  replication_converter_instance_type: m5.xlarge
  # Instance type for replication instances for any new CloudEndure project
  replication_instance_type: m5.large
  # Security group IDs to bind to the destination instance, in the cutover subnet
  target_security_group_ids:
    - sg-0a512345678
  # Subnet ID where to create the destination instances
  target_subnet_id: subnet-0a512345678
  # Security group IDs to bind to the destination instance, in the test subnet
  test_security_group_ids:
    - sg-0a512345678
  # Subnet ID where to create the destination test instances, before the cutover
  test_subnet_id: subnet-0a512345678
  # AWS account ID of the environment
  account_id: 12345678790
  # IAM role to attach to all destination instances
#  iam_role:
  # Security group ID to be duplicated and attach to any destination instance (test & cutover).
  # Will be merged with Security Group IDs defined as defaults
#  template_security_group_id: sg-0a512345678
  # Tenancy for the servers: "Shared", "Dedicated" or "Dedicated Host"
#  tenancy: Shared
  # Server type: windows or linux
#  server_os: windows
  # Tags: Default tags to be add to migration-tags.csv
#  tags:
#    Name:
#    Criticity: critical  
