# This configuration file contains default values for CloudEndure migration factory

# Environment name (this is a logical container for default values - can represent a wave, a workload, an account or anything else)
# You can duplicate this block if you have multiple environments
environment:
  # Subnet where the replication servers for CloudEndure will be created
  replication_subnet_id: subnet-0a512345678
  # Security group IDs to bind to the destination instance, in the cutover subnet
  target_security_group_ids:
    - sg-0a512345678
  # Subnet ID where to create the destination instances
  target_subnet_id: subnet-0a512345678
  # Security group IDs to bind to the destination instance, in the test subnet
  test_security_group_ids:
    - sg-0a512345678
  # Subnet ID where to create the destination test instances, before the cutover
  test_subnet_id: subnet-0a512345678
  # IAM role to attach to all destination instances
  iam_role:
  # Security group ID to be duplicated and attach to any destination instance (test & cutover).
  # Will be merged with Security Group IDs defined as defaults
  template_security_group_id: sg-0a512345678
  # AWS account ID of the environment
  account_id: 12345678790
