#!/usr/bin/env python3

from __future__ import print_function
import sys
import argparse
import subprocess
import logging

import mf
from mf.utils import EnvironmentVariableFetcher
from mf.config_loaders import EndpointsLoader
from mf.migration_factory import MigrationFactoryRequester, MfField


class WindowsProxyAdder:
    """Add proxy for Windows servers"""

    _arguments: argparse.Namespace = None
    _endpoints_loader: EndpointsLoader = None
    _migration_factory_requester: MigrationFactoryRequester = None

    def __init__(self):
        parser = argparse.ArgumentParser()
        parser.add_argument('--wave-name', required=True)
        parser.add_argument('--proxy-server-address', required=True)
        parser.add_argument(
            '--config-file-endpoints',
            default=EnvironmentVariableFetcher.fetch(
                env_var_names=mf.ENV_VAR_ENDPOINT_CONFIG_FILE,
                default=mf.DEFAULT_ENV_VAR_ENDPOINT_CONFIG_FILE
            ),
            help='Configuration file containing the Migration Factory endpoint URLs'
        )
        self._arguments = parser.parse_args(parser)

        self._endpoints_loader = EndpointsLoader(endpoint_config_file=self._arguments.config_file_endpoints)
        self._migration_factory_requester = MigrationFactoryRequester(self._endpoints_loader)

        logging.getLogger('root').debug(self._arguments)

    def add_proxy(self):
        server_list = self._migration_factory_requester.get_user_servers_by_wave_and_os(
            filter_wave_name=self._arguments.wave_name, filter_os='windows')

        for server in server_list:
            command1 = "Invoke-Command -ComputerName " + \
                server[MfField.SERVER_FQDN] + \
                " -ScriptBlock {[Environment]::SetEnvironmentVariable('https_proxy', 'https://" + \
                self._arguments.proxy_server_address + "/', 'Machine')}"
            command2 = "Invoke-Command -ComputerName " + \
                server[MfField.SERVER_FQDN] + \
                " -ScriptBlock {Set-ItemProperty -path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings' ProxyEnable -value 1}"
            command3 = "Invoke-Command -ComputerName " + \
                server[MfField.SERVER_FQDN] + \
                " -ScriptBlock {Set-ItemProperty -path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings' ProxyServer -value " + \
                self._arguments.proxy_server_address + "}"
            p1 = subprocess.Popen(["powershell.exe", command1], stdout=sys.stdout)
            p1.communicate()
            p2 = subprocess.Popen(["powershell.exe", command2], stdout=sys.stdout)
            p2.communicate()
            p3 = subprocess.Popen(["powershell.exe", command3], stdout=sys.stdout)
            p3.communicate()
            print("Proxy server added for server: " + server)


if __name__ == '__main__':
    windows_proxy_adder = WindowsProxyAdder()
    windows_proxy_adder.add_proxy()
