#!/usr/bin/env python3

import argparse
import datetime
import logging
import os
import pytz

import mf
from mf.config_loaders import ConfigLoader, DefaultsLoader
from mf.notification import Notifier
from mf.utils import EnvironmentVariableFetcher


class WaveMigrationEstimator:
    """ Estimate the amount of time to replicate, test and do the cutover """

    DEFAULT_MBPS_SPEED = 1000

    REPLICATION_BEST_TIME_COEFFICIENT = 0.9
    REPLICATION_WORST_TIME_COEFFICIENT = 0.6

    _arguments = []
    _path_wave = None
    _config_loader = None
    _notifier = None
    _default_mbps_speed = DEFAULT_MBPS_SPEED
    _work_hours_start = None
    _work_hours_end = None
    _work_hours_pause_start = None
    _work_hours_pause_end = None
    _minimal_test_duration = None
    _warmup_time_before_replication = None
    _close_time_after_replication = None
    _timezone = None

    def __init__(self):
        parser = argparse.ArgumentParser()
        parser.add_argument('-v', action='store_true', help='Enable info outputs')
        parser.add_argument('-vv', action='store_true', help='Enable debug outputs')
        parser.add_argument('--wave-name', required=True, help='Name of the wave to delete')
        parser.add_argument('--notify', action='store_true', help='Whether or not to notify the results')
        parser.add_argument('--default-mbps-speed', default=self.DEFAULT_MBPS_SPEED, help='Default speed in Mbit/s')
        parser.add_argument('--work-hours-start', default=None, help='Shift start hour')
        parser.add_argument('--work-hours-end', default=None, help='Shift leave hour')
        parser.add_argument('--work-hours-pause-start', default=None, help='Lunch break hour')
        parser.add_argument('--work-hours-pause-end', default=None, help='Lunch break hour end')
        parser.add_argument('--timezone', default=None, help='Timezone to use to compile results')
        parser.add_argument(
            '--minimal-test-duration',
            default=None,
            help='Amount of time in hours required to test'
        )
        parser.add_argument(
            '--warmup-time-before-replication',
            default=None,
            help='Estimation of the amount of time in seconds before replication starts'
        )
        parser.add_argument(
            '--close-time-after-replication',
            default=None,
            help='Estimation of the amount of time in seconds to complete replication after data transfer ends'
        )
        parser.add_argument(
            '--total-disk-size',
            required=True,
            help='Total disk size in GB in this wave'
        )
        parser.add_argument(
            '--config-file-defaults',
            default=EnvironmentVariableFetcher.fetch(
                env_var_names=mf.ENV_VAR_DEFAULTS_CONFIG_FILE,
                default=mf.DEFAULT_ENV_VAR_DEFAULTS_CONFIG_FILE
            ),
            help='Configuration file containing default IDs'
        )
        environment_arg = parser.add_argument('--environment', help='Environment of the wave')

        self._arguments = parser.parse_args()

        mf.setup_logging(logging, self._arguments.v, self._arguments.vv)
        defaults_loader = DefaultsLoader()
        self._defaults = defaults_loader.load(
            default_config_file=self._arguments.config_file_defaults,
            environment=self._arguments.environment
        )

        environment_arg.choices = defaults_loader.get_available_environments()

        self._arguments = parser.parse_args()
        self._path_wave = os.path.join(mf.PATH_HOME, self._arguments.wave_name)
        self._config_loader = ConfigLoader()
        self._notifier = Notifier(self._config_loader.get_notifications_config())
        self._assign_configuration_values()

    def estimate(self):
        buffer = "    ##################################################################################\n"

        buffer += "    Estimation for the **{}** wave, with total disk size at {}GB and a speed of {}Mbps \n".format(
            self._arguments.wave_name,
            self._arguments.total_disk_size,
            self._default_mbps_speed
        )
        buffer += "    ##################################################################################\n\n"

        best_duration_in_seconds = int(self._get_disk_size_in_mega_bytes() / self._get_best_speed_in_mega_bytes())
        best_replication_end_date = self._get_replication_end_date(best_duration_in_seconds)
        buffer += "### Best:  with a speed of {}MB/s, the replication would end in about \033[1m{} ({})\033[0m.\n".format(
            self._get_best_speed_in_mega_bytes(),
            self._get_formatted_replication_time(best_duration_in_seconds),
            self._get_formatted_replication_end_date(best_replication_end_date)
        )

        worst_duration_in_seconds = int(self._get_disk_size_in_mega_bytes() / self._get_worst_speed_in_mega_bytes())
        worst_replication_end_date = self._get_replication_end_date(worst_duration_in_seconds)
        buffer += "### Worst: with a speed of {}MB/s, the replication would end in about \033[1m{} ({})\033[0m.\n".format(
            self._get_worst_speed_in_mega_bytes(),
            self._get_formatted_replication_time(worst_duration_in_seconds),
            self._get_formatted_replication_end_date(worst_replication_end_date)
        )

        estimated_test_date = self._get_estimated_test_date(worst_duration_in_seconds)

        buffer += "### By starting the replication immediately, tests could be started \033[1m{}\033[0m.\n".format(
            'on {} {}'.format(estimated_test_date.strftime('%A'), estimated_test_date.strftime('%-d'))
        )

        estimated_cutover_date = self._get_estimated_cutover_date(estimated_test_date)

        buffer += "### By starting the replication immediately, cutover could be performed \033[1m{}\033[0m.\n".format(
            'starting {} {}, around {}h'.format(
                estimated_cutover_date.strftime('%A'),
                estimated_cutover_date.strftime('%-d'),
                estimated_cutover_date.strftime('%H')
            )
        )

        print(buffer)

        if self._arguments.notify:
            self._notifier.notify(Notifier.ESTIMATION_DONE, buffer)

    def _assign_configuration_values(self):
        if self._arguments.default_mbps_speed == self.DEFAULT_MBPS_SPEED:
            self._default_mbps_speed = self._defaults.get('replication_bandwidth_throttling', self.DEFAULT_MBPS_SPEED)

        estimation_config = self._config_loader.get_estimations_config()
        if self._arguments.work_hours_start is None:
            self._work_hours_start = estimation_config['work_hours_start']
        if self._arguments.work_hours_end is None:
            self._work_hours_end = estimation_config['work_hours_end']
        if self._arguments.work_hours_pause_start is None:
            self._work_hours_pause_start = estimation_config['work_hours_pause_start']
        if self._arguments.work_hours_pause_end is None:
            self._work_hours_pause_end = estimation_config['work_hours_pause_end']
        if self._arguments.minimal_test_duration is None:
            self._minimal_test_duration = estimation_config['minimal_test_duration']
        if self._arguments.warmup_time_before_replication is None:
            self._warmup_time_before_replication = estimation_config['warmup_time_before_replication']
        if self._arguments.close_time_after_replication is None:
            self._close_time_after_replication = estimation_config['close_time_after_replication']
        if self._arguments.timezone is None:
            self._timezone = estimation_config['timezone']

    def _get_disk_size_in_mega_bytes(self) -> int:
        return int(self._arguments.total_disk_size) * 1000

    def _get_speed_in_mega_bytes(self, coefficient: int) -> float:
        return (self._default_mbps_speed * coefficient) / 8

    def _get_worst_speed_in_mega_bytes(self) -> float:
        return (self._default_mbps_speed * self.REPLICATION_WORST_TIME_COEFFICIENT) / 8

    def _get_best_speed_in_mega_bytes(self) -> float:
        return (self._default_mbps_speed * self.REPLICATION_BEST_TIME_COEFFICIENT) / 8

    def _get_formatted_replication_time(self, seconds: int) -> str:
        seconds += self._warmup_time_before_replication + self._close_time_after_replication

        days = seconds // (24 * 3600)
        hours = (seconds % (24 * 3600)) // 3600
        minutes = (seconds % 3600) // 60
        seconds %= 60

        result = ''
        if days >= 1:
            result = result + '{} day'.format(str(days))

        if days >= 2:
            result = result + 's'

        if hours >= 1:
            if days >= 1:
                result = result + ' and '

            result = result + '{} hour'.format(str(hours))

        if hours >= 2:
            result = result + 's'

        if minutes >= 1 and days == 0:
            if hours >= 1:
                result = result + ' and '

            result = result + '{} minute'.format(str(minutes))

        if minutes >= 2 and days == 0:
            result = result + 's'

        return result

    def _get_formatted_replication_end_date(self, replication_end_date: datetime) -> str:
        result = ''
        if replication_end_date.day == self._get_now_timezoned().day:
            result += 'today'
        elif (replication_end_date - self._get_now_timezoned()).days == 1:
            result += 'tomorrow'
        elif (replication_end_date - self._get_now_timezoned()).days >= 2:
            result += '{} {}'.format(replication_end_date.strftime('%A'), replication_end_date.strftime('%-d'))

        return result

    def _get_replication_end_date(self, seconds_to_replicate: int) -> datetime:
        logging.getLogger('root').debug("{}: Replication time is: {}".format(
            self.__class__.__name__,
            datetime.timedelta(seconds=seconds_to_replicate)
        ))

        replication_end_date = self._get_now_timezoned() + datetime.timedelta(seconds=seconds_to_replicate)

        logging.getLogger('root').debug("{}: Replication end date is: {}".format(
            self.__class__.__name__,
            replication_end_date.ctime()
        ))

        return replication_end_date

    def _get_estimated_test_date(self, seconds_to_replicate: int) -> datetime:
        test_can_be_started_date = self._get_now_timezoned() + datetime.timedelta(seconds=seconds_to_replicate)

        logging.getLogger('root').debug("{}: Test can be started date without delay: {}".format(
            self.__class__.__name__,
            test_can_be_started_date.ctime()
        ))

        return self._delay_date_for_working_hours(test_can_be_started_date)

    def _get_estimated_cutover_date(self, test_can_be_started_date: datetime) -> datetime:
        test_end_date = test_can_be_started_date + datetime.timedelta(hours=self._minimal_test_duration)

        logging.getLogger('root').debug("{}: Cutover can be performed date without delay: {}".format(
            self.__class__.__name__,
            test_end_date.ctime()
        ))

        return self._delay_date_for_working_hours(test_end_date)

    def _delay_date_for_working_hours(self, date_to_delay: datetime) -> datetime:
        date_to_delay_day = date_to_delay.strftime('%a')
        date_to_delay_hour = int(date_to_delay.strftime('%H'))

        if date_to_delay_hour >= self._work_hours_end:
            date_to_delay = date_to_delay + datetime.timedelta(
                hours=(24 - date_to_delay_hour) + self._work_hours_start
            )
            date_to_delay_day = date_to_delay.strftime('%a')
            date_to_delay_hour = int(date_to_delay.strftime('%H'))
        if date_to_delay_hour < self._work_hours_start:
            date_to_delay = date_to_delay + datetime.timedelta(
                hours=(self._work_hours_start - date_to_delay_hour)
            )
            date_to_delay_day = date_to_delay.strftime('%a')
            date_to_delay_hour = int(date_to_delay.strftime('%H'))
        if date_to_delay_hour >= self._work_hours_pause_start and date_to_delay_hour < self._work_hours_pause_end:
            date_to_delay = date_to_delay + datetime.timedelta(hours=1)
            date_to_delay_day = date_to_delay.strftime('%a')
            date_to_delay_hour = int(date_to_delay.strftime('%H'))

        if date_to_delay_day == 'Sat':
            date_to_delay = date_to_delay + datetime.timedelta(days=2)
            test_can_be_started_day = date_to_delay.strftime('%a')

        elif date_to_delay_day == 'Sun':
            date_to_delay = date_to_delay + datetime.timedelta(days=1)
            test_can_be_started_day = date_to_delay.strftime('%a')

        logging.getLogger('root').debug("{}: Delayed date: {}".format(
            self.__class__.__name__,
            date_to_delay.ctime()
        ))

        return date_to_delay

    def _get_now_timezoned(self) -> datetime:
        utc_now = pytz.utc.localize(datetime.datetime.utcnow())
        return utc_now.astimezone(pytz.timezone(self._timezone))


if __name__ == '__main__':
    wave_migration_estimator = WaveMigrationEstimator()
    wave_migration_estimator.estimate()
