#!/usr/bin/env python3

from __future__ import print_function

import argparse
import json
import logging
import os
import time
from math import ceil

import mf
import mf_install_linux_package
from mf.aws import AWSServiceAccessor
from mf.cloud_endure import CloudEndureRequester
from mf.config_loaders import EndpointsLoader, ConfigLoader
from mf.migration_factory import MigrationFactoryRequester, MfField
from mf.notification import Notifier
from mf.utils import EnvironmentVariableFetcher, PowershellRunner


class AwsCliInstaller:
    """
        Install Aws Cli on a distant machine
        Works with Linux or Windows hosts.
    """

    _path: str = None
    _domain_password: str = None
    _cloud_endure_requester: CloudEndureRequester = None
    _migration_factory_requester: MigrationFactoryRequester = None
    _endpoints_loader: EndpointsLoader = None
    _aws_service_accessor: AWSServiceAccessor = None
    _config_loader: ConfigLoader = None
    _notifier: Notifier = None

    def __init__(self):
        parser = argparse.ArgumentParser(__doc__)
        parser.add_argument('-v', action='store_true', help='Enable info outputs')
        parser.add_argument('-vv', action='store_true', help='Enable debug outputs')
        parser.add_argument('--skip-notify', action='store_true', help='Whether or not to notify the results')
        parser.add_argument('--wave-name', required=True, help='Name of the wave to act on')
        parser.add_argument('--windows-username', default=EnvironmentVariableFetcher.fetch(
            env_var_names=mf.ENV_VAR_WINDOWS_USERNAME,
            default=''
        ),
            help="The windows username"
        )
        parser.add_argument('--linux-username', default=EnvironmentVariableFetcher.fetch(
            env_var_names=mf.ENV_VAR_LINUX_USERNAME,
            default=''
        ),
            help="The linux username"
        )
        parser.add_argument('--linux-private-key-file', default=EnvironmentVariableFetcher.fetch(
            env_var_names=mf.ENV_VAR_LINUX_PRIVATE_KEY_FILE,
            default=''
        ),
            help="The linux private key file"
        )
        parser.add_argument(
            '--config-file-endpoints',
            default=EnvironmentVariableFetcher.fetch(
                env_var_names=mf.ENV_VAR_ENDPOINT_CONFIG_FILE,
                default=mf.DEFAULT_ENV_VAR_ENDPOINT_CONFIG_FILE
            ),
            help='Configuration file containing the Migration Factory endpoint URLs'
        )

        self._arguments = parser.parse_args()

        mf.setup_logging(logging, self._arguments.v, self._arguments.vv)

        self._endpoints_loader = EndpointsLoader(endpoint_config_file=self._arguments.config_file_endpoints)
        self._migration_factory_requester = MigrationFactoryRequester(
            self._endpoints_loader
        )
        self._cloud_endure_requester = CloudEndureRequester()

        self._aws_service_accessor = AWSServiceAccessor()

        if self._has_windows_user():
            self._domain_password = EnvironmentVariableFetcher.fetch(
                env_var_names=mf.ENV_VAR_WINDOWS_PASSWORD,
                env_var_description='Windows password',
                default='',
                sensitive=True
            )

        self._config_loader = ConfigLoader()
        self._notifier = Notifier(self._config_loader.get_notifications_config())

    def install(self):
        self._install_windows_cli()
        self._install_linux_cli()
        self._agent_check()

    def _install_windows_cli(self):
        print('### Install Windows CloudEndure agent…', end=' ')

        _server_list = self._migration_factory_requester.get_user_servers_by_wave_and_os(
            filter_wave_name=self._arguments.wave_name,
            filter_os='windows'
        )

        if not _server_list:
            print('✔ No Windows server in this wave. Nothing to do')
            return

        _api_tokens = self._get_api_tokens()

        logging.getLogger('root').debug(
            self.__class__.__name__ + ':api token: “{}”'.format(_api_tokens)
        )

        if _api_tokens is None:
            return

        for server in _server_list:
            install_command = os.path.dirname(os.path.abspath(__file__)) + '/mf_download_windows_aws_cli.ps1 "No" "' + \
                _api_tokens[server[MfField.APP_ID]] + '" "' + server[MfField.SERVER_FQDN] + '"'

            if self._has_windows_user():
                install_command += ' "' + self._arguments.windows_username + '" "' + self._domain_password + '"'

            logging.getLogger('root').info(
                self.__class__.__name__ + ':Running “{}”'.format(install_command)
            )

            PowershellRunner.run(install_command)

        print('✔ done.')

    def _install_linux_cli(self):
        print('### Install Linux CloudEndure agent…', end=' ')

        _server_list = self._migration_factory_requester.get_user_servers_by_wave_and_os(
            filter_wave_name=self._arguments.wave_name, filter_os='linux'
        )

        if not _server_list:
            print('✔ No Linux server in this wave. Nothing to do.')
            return

        _api_tokens = self._get_api_tokens()

        if _api_tokens is None:
            return

        if self._arguments.linux_username.lower().strip() != '':
            user_name = self._arguments.linux_username
        else:
            user_name = EnvironmentVariableFetcher.fetch(
                env_var_names=mf.ENV_VAR_LINUX_USERNAME, env_var_description='Linux username'
            )

        has_key = self._arguments.linux_private_key_file.lower().strip() != ''
        if has_key:
            pass_key = self._arguments.linux_private_key_file
        else:
            pass_key = EnvironmentVariableFetcher.fetch(
                env_var_names=mf.ENV_VAR_LINUX_PASSWORD, env_var_description='Linux password', sensitive=True
            )

        for server in _server_list:
            mf_install_linux_package.install_cloud_endure(
                server[MfField.SERVER_FQDN],
                user_name,
                pass_key,
                'y' if has_key else 'n',
                _api_tokens[server[MfField.APP_ID]]
            )

        print('✔ done.')

    def _get_api_tokens(self):
        _apps = self._migration_factory_requester.get_user_apps_by_wave_name(wave_name=self._arguments.wave_name)

        if _apps is None:
            logging.getLogger('root').info('{}: wave “{}” don\'t have cloudendure project)'.format(
                self.__class__.__name__, self._arguments.wave_name
            ))
            return None

        _installation_token_by_app_id = {}

        for app in _apps:
            if MfField.CLOUDENDURE_PROJECT_NAME not in app:
                logging.getLogger('root').info('{}: app “{}” don\'t have cloudendure project)'.format(
                    self.__class__.__name__, app[MfField.APP_NAME]
                ))
                continue

            _installation_token_by_app_id[app[MfField.APP_ID]] = self._cloud_endure_requester.get_api_token(
                project_name=app[MfField.CLOUDENDURE_PROJECT_NAME]
            )

        return _installation_token_by_app_id

    def _has_windows_user(self):
        return self._arguments.windows_username != ""

    def _is_server_in_cloudendure_by_name(self, wave_name: str, server_name: str):
        return self._cloud_endure_requester.get_machine(wave_name, server_name) is not None

    def _agent_check(self):
        _server_list = self._migration_factory_requester.get_user_servers_by_wave(
            filter_wave_name=self._arguments.wave_name)

        for server in _server_list:
            is_agent_installed = False
            for i in range(1, 5):
                if self._is_server_in_cloudendure_by_name(
                    self._arguments.wave_name, server[MfField.SERVER_FQDN]
                ) or self._is_server_in_cloudendure_by_name(self._arguments.wave_name, server[MfField.SERVER_NAME]):
                    self._migration_factory_requester.put(
                        MigrationFactoryRequester.URI_USER_SERVER.format(server[MfField.SERVER_ID]),
                        data=json.dumps({"migration_status": "CE Agent Install - Success"})
                    )
                    print("{} ✔ Success".format(server[MfField.SERVER_FQDN]))
                    if not self._arguments.skip_notify:
                        self._notifier.notify(
                            Notifier.AGENT_INSTALLED,
                            Notifier.AGENT_INSTALLED_MESSAGE.format(server[MfField.SERVER_FQDN],
                                                                    self._arguments.wave_name)
                        )
                    is_agent_installed = True
                    break
                # exponential backoff algorithm
                logging.getLogger('root').debug(
                    self.__class__.__name__ + ': Retry “{}”/4'.format(i)
                )
                time.sleep(ceil(((2 ** i) - 1) / 2) * 5)

            if is_agent_installed:
                continue

            self._migration_factory_requester.put(
                MigrationFactoryRequester.URI_USER_SERVER.format(server[MfField.SERVER_ID]),
                data=json.dumps({"migration_status": "CE Agent Install - Failed"})
            )
            print("{} ✗ Failed".format(server[MfField.SERVER_FQDN]))


if __name__ == '__main__':
    ce_agent_installer = AwsCliInstaller()
    ce_agent_installer.install()
