#!/usr/bin/env python3

from __future__ import print_function
import sys
import argparse
import requests
import json
import subprocess
import time
import getpass
import os

import mf
from mf.utils import EnvironmentVariableFetche
from mf.config_loaders import EndpointsLoader

serverendpoint = '/prod/user/servers'
appendpoint = '/prod/user/apps'

def Factorylogin(username, password, LoginHOST):
    login_data = {'username': username, 'password': password}
    r = requests.post(LoginHOST + '/prod/login',
                  data=json.dumps(login_data))
    if r.status_code == 200:
        print("Migration Factory : You have successfully logged in")
        print("")
        token = str(json.loads(r.text))
        return token
    if r.status_code == 502:
        print("ERROR: Incorrect username or password....")
        sys.exit(1)
    else:
        print(r.text)
        sys.exit(2)

def ServerList(waveid, token, UserHOST):
# Get all Apps and servers from migration factory
    auth = {"Authorization": token}
    servers = json.loads(requests.get(UserHOST + serverendpoint, headers=auth).text)
    #print(servers)
    apps = json.loads(requests.get(UserHOST + appendpoint, headers=auth).text)
    #print(apps)

    # Get App list
    applist = []
    for app in apps:
        if 'wave_id' in app:
            if str(app['wave_id']) == str(waveid):
                applist.append(app['app_id'])

    #print(apps)
    #print(servers)
    # Get Server List
    serverlist = []
    for app in applist:
        for server in servers:
            if app == server['app_id']:
                if 'server_os' in server:
                    if 'server_fqdn' in server:
                        if server['server_os'].lower() == "windows":
                            serverlist.append(server['server_fqdn'])
                    else:
                        print("ERROR: server_fqdn for server: " + server['server_name'] + " doesn't exist")
                        sys.exit(4)
                else:
                    print ('server_os attribute does not exist for server: ' + server['server_name'] + ", please update this attribute")
                    sys.exit(2)
    if len(serverlist) == 0:
        print("ERROR: Windows Serverlist for wave: " + waveid + " is empty....")
        sys.exit(5)
        print("")
    else:
        print("successfully retrived server list")
        for server in serverlist:
            print(server)
        return serverlist

def main(arguments):
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--Waveid', required=True)
    parser.add_argument('--WindowsUser', default = os.environ.get('MF_WINDOWS_USERNAME', ''), help= "This can also be set in environment variable MF_ENDPOINT_CONFIG_FILE")
    parser.add_argument(
           '--config-file-endpoints',
           default=EnvironmentVariableFetcher.fetch(
               env_var_names=mf.ENV_VAR_ENDPOINT_CONFIG_FILE,
               default=mf.DEFAULT_ENV_VAR_ENDPOINT_CONFIG_FILE
           ),
           help='Configuration file containing the Migration Factory endpoint URLs'
       )
    args = parser.parse_args(arguments)

    _endpoints_loader = EndpointsLoader(endpoint_config_file=self.args.config_file_endpoints)
    LoginHOST = _endpoints_loader.get_login_api_url()
    UserHOST = _endpoints_loader.get_user_api_url()

    Domain_User = args.WindowsUser

    choice_flag = True
    choice = 3
    while choice_flag:
        print("1. Create user")
        print("2. Delete user")
        print("3. Exit")
        choice = input("Enter your choice [1-3]: ")
        if choice == '3':
            sys.exit(0)
        elif choice != '1' and choice != '2':
            print("Please provide a valid option [1, 2, 3]")
            print("")
        else:
            choice_flag = False
    print("****************************")
    print("*Login to Migration factory*")
    print("****************************")

    if 'MF_USERNAME' not in os.environ:
        username = input('Factory Username: ')
    else:
        username = os.getenv('MF_USERNAME')
    if 'MF_PASSWORD' not in os.environ:
        password = getpass.getpass('Factory Password: ')
    else:
        password = os.getenv('MF_PASSWORD')

    token = Factorylogin(username, password, LoginHOST)

    print("****************************")
    print("*Getting Server List*")
    print("****************************")
    Servers = ServerList(args.Waveid, token, UserHOST)
    print("")
    if Domain_User != "":
      if 'MF_WINDOWS_PASSWORD' not in os.environ:
            Domain_Password = getpass.getpass("Windows User Password: ")
      else:
            Domain_Password = os.getenv('MF_WINDOWS_PASSWORD')
    if choice == '1':
        print("")
        print("************************************")
        print("*Creating local admin on the server*")
        print("************************************")
        LocalAdminUser = input("Enter Local admin username: ")
        localadmin_pass_first = getpass.getpass('Local admin Password: ')
        localadmin_pass_second = getpass.getpass('Re-enter Password: ')
        while(localadmin_pass_first != localadmin_pass_second):
            print("Password mismatch, please try again!")
            localadmin_pass_first = getpass.getpass('Local admin Password: ')
            localadmin_pass_second = getpass.getpass('Re-enter Password: ')
        localadmin_pass = localadmin_pass_second
        print("")
        for s in Servers:
            command1 = "Invoke-Command -ComputerName " + s + " -ScriptBlock {net user " + LocalAdminUser + " " + localadmin_pass + " /add}"
            if Domain_User != "":
              command1 += " -Credential (New-Object System.Management.Automation.PSCredential('" + Domain_User + "', (ConvertTo-SecureString '" + Domain_Password + "' -AsPlainText -Force))) -Authentication Negotiate"
            print("------------------------------------------------------")
            print("- Creating a local user on: " + s + " -")
            print("------------------------------------------------------")
            p = subprocess.Popen(["pwsh", "-Command", command1], stdout=sys.stdout)
            p.communicate()
            command2 = "Invoke-Command -ComputerName " + s + " -ScriptBlock {net localgroup Administrators " + LocalAdminUser + " /add}"
            if Domain_User != "":
              command2 += " -Credential (New-Object System.Management.Automation.PSCredential('" + Domain_User + "', (ConvertTo-SecureString '" + Domain_Password + "' -AsPlainText -Force))) -Authentication Negotiate"
            print("Adding user to local admin group on server: " + s)
            p = subprocess.Popen(["pwsh", "-Command", command2], stdout=sys.stdout)
            p.communicate()
        print("")
    else:
        print("")
        print("*************************************")
        print("*Deleting local admin on the servers*")
        print("*************************************")
        print("")
        LocalAdminUser = input("Enter local admin UserName to be deleted: ")
        print("")
        for s in Servers:
            command1 = "Invoke-Command -ComputerName " + s + " -ScriptBlock {net user " + LocalAdminUser + " /delete}"
            if Domain_User != "":
              command1 += " -Credential (New-Object System.Management.Automation.PSCredential('" + Domain_User + "', (ConvertTo-SecureString '" + Domain_Password + "' -AsPlainText -Force))) -Authentication Negotiate"
            print("------------------------------------------------------")
            print("- Deleting a local user on: " + s + " -")
            print("------------------------------------------------------")
            p = subprocess.Popen(["pwsh", "-Command", command1], stdout=sys.stdout)
            p.communicate()

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
